- build:
		protoc --go_out=plugins=grpc:../micro user.proto
		protoc --go_out=plugins=grpc:../micro group.proto
		protoc --go_out=plugins=grpc:../micro board.proto
		protoc --go_out=plugins=grpc:../micro calendar.proto
		